# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: '3.6'

services:
  ## Define influxdb connector service
  ia_influxdbconnector:
    depends_on:
      - ia_common
    build:
      context: $PWD/../InfluxDBConnector
      dockerfile: $PWD/../InfluxDBConnector/Dockerfile
      args:
        UBUNTU_IMAGE_VERSION: ${UBUNTU_IMAGE_VERSION}
        EII_VERSION: ${EII_VERSION}
        EII_UID: ${EII_UID}
        EII_USER_NAME: ${EII_USER_NAME}
        INFLUXDB_VERSION: ${INFLUXDB_VERSION}
        CMAKE_INSTALL_PREFIX: ${EII_INSTALL_PATH}
        EII_INSTALL_PATH: ${EII_INSTALL_PATH}
    read_only: true
    ipc: "none"
    security_opt:
    - no-new-privileges
    healthcheck:
      test: ["CMD-SHELL", "exit", "0"]
      interval: 5m
    image: ${DOCKER_REGISTRY}openedgeinsights/ia_influxdbconnector:${EII_VERSION}
    container_name: ia_influxdbconnector
    hostname: ia_influxdbconnector
    restart: unless-stopped
    environment:
      AppName: "InfluxDBConnector"
      DEV_MODE: ${DEV_MODE}
      PROFILING_MODE: ${PROFILING_MODE}
      no_proxy: ${ETCD_HOST}
      NO_PROXY: ${ETCD_HOST}
      ETCD_HOST: ${ETCD_HOST}
      ETCD_CLIENT_PORT: ${ETCD_CLIENT_PORT}
      ETCD_PREFIX: ${ETCD_PREFIX}
      INFLUXDB_TLS_CIPHERS: ${TLS_CIPHERS}
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
    volumes:
      - "vol_influxdb_data:/influxdata"
      - "${EII_INSTALL_PATH}/sockets:${SOCKET_DIR}"
      - ./Certificates/InfluxDBConnector:/run/secrets/InfluxDBConnector:ro
      - ./Certificates/rootca/cacert.pem:/run/secrets/rootca/cacert.pem:ro
      - "vol_influxdb_conf:/tmp/influxdb"
    ports:
      - "$INFLUXDB_PORT:$INFLUXDB_PORT"
      - 65145:65145
      - 65030:65030
      - 65031:65031
      - 65032:65032
      - 65033:65033
      - 65034:65034
    networks:
      - eii

volumes:
  vol_influxdb_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  vol_influxdb_conf:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs

